### ISSUE TITLE
General cleanup

### ISSUE THREAD

**Issue by SilasPeters** [svsticky/radio#129]
There are several minor things which can be done to improve the maintainability of r.a.d.i.o., some of which can prevent a future break in our system.

- [ ] Remove `scrollIntoView`
  - We currently use a package for automatically scrolling something into view, while this feature [is already supported by modern browsers](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)
- [ ] Remove `moment`
  - `moment` is a package used to get the current date. I was told it was slow and old, so we might want to replace it.
- [x] Get rid of deprecated features
    - Like `findDOMnode` in `Activity.jsx`, we should remove deprecated stuff.
- [ ] Get rid of `babel`
  - This might be the most important thing in here. It his highly deprecated, and our build can break any time. Whilst we do not directly use it, some packages are dependent on babel. We need to find and exterminate those packages - or ask them to leave.
  - NPM even gives us a big warning about this when running the linter.

**Comment by stickyPiston** [comment]
An update for this issue:
- the first point is implemented in ccd5d72db5c94f515925a4dbd8b8d668051b608b (in #142),
- the last point is implemented in #144, since the deprecation warning most likely came from the create-react-app config which is not maintained anymore
