### ISSUE TITLE
Gif posters are not properly displayed

### ISSUE THREAD

**Issue by SilasPeters** [svsticky/radio#131]
Previously, if a poster was a gif, it would be displayed like any other poster but animated.

Currently, the picture does not seem to load, and the poster of the previous activity is (still) shown instead.

The exact problem, is that large GIFs are not loaded in time (before the next activity is displayed), and thus the loading gets cut off. If it never fully loads, it will never be cached.

A solution would be to load all images in the background, somehow.

**Comment by stickyPiston** [comment]
Another solution for this problem is fixing #109, videos have support for streaming which means that smaller buffers need to be loaded instead of the whole gif all at once.

**Comment by SilasPeters** [comment]
Just noting that we had the idea of streaming a video instead
