### ISSUE TITLE
Remove placeholder code

### ISSUE THREAD

**Issue by tomwassenberg** [svsticky/radio#33]
During yesterday's IT Crowd session we noticed that RADIO always makes a request to https://radio.svsticky.nl/placeholder, which does not exist.

Even it it would work, Koala should be the place to put this logic in (it's partially already [there](https://github.com/svsticky/constipated-koala/blob/master/config/application.rb#L56), but not working yet). So the broken placeholder logic in RADIO should be removed.

@arianvp already tested that the SVG placeholder would render fine.

**Comment by Riscky** [comment]
This should be fixed now the whole thing is rewritten
