### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by Riscky** [svsticky/radio#64]
We should set up a CircleCI instance to enforce eslint and check if the builds succeed.
Maybe we could even add some tests.

**Comment by Riscky** [comment]
Or maybe CD to Netlify so PRs could be verified visually

**Comment by SilasPeters** [comment]
Reviving this issue haha. I understand that you are referring to the PR preview feature from Netlify, so that the resulting radio can be accessed from a temporary URL.

Why would we want this? Previewing it using `npm run preview` should suffice right?

**Comment by Riscky** [comment]
Wow you're digging through the graveyard, aren't you? I guess I wanted a CI pipeline, and later also figured we could CD to netlify. Doesn't really seem to be worth it for this project though haha.

**Comment by SilasPeters** [comment]
Alright thanks haha
