### ISSUE TITLE
Do less requests

### ISSUE THREAD

**Issue by Riscky** [svsticky/radio#88]
Apparently Radio does about 2 requests per seconds, which is way more then necessary. Lets not :)

**Comment by Riscky** [comment]
It appears to be a caching problem

**Comment by Riscky** [comment]
Posters are cached now, but the amount of requests for renewing the activities is still a bit over the top

**Comment by Casjur** [comment]
Activities loading are no longer a problem (since a while?). 

(However, there currently is an ad of 100mb💀 which is unable to be cached and takes so long to load that it is almost skipped)

**Comment by stickyPiston** [comment]
Since #140, we now have RTK Query to handle caching (and invalidating) of the activities, quotes, board posts and commits. The activity posters will also be cached by the browser after they are requested a few times.
